language: node_js

addons:
  chrome: stable

services:
  - xvfb

git:
  depth: 5

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - npm install -g @skyux-sdk/cli
  - skyux version
  - skyux certs install

# Identical to package.json except for travis wait
script:
  - skyux lint && skyux test && skyux e2e && travis_wait skyux build --logFormat none --output-keep-alive
